
function onLoad()
  
  shared.courtCards = {
    [1800] = {
      cardNum = 1,
      rank = 3,
      suit = suitIds.Intelligence,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = { 
        actionIds.March,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1801] = {
      cardNum = 2,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.Army,
        onPlayedIds.FavorMilitary,
      },
      actions = {
        actionIds.Battle,
        actionIds.March
      },
      special = false,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1802] = {
      cardNum = 3,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.Army,
        onPlayedIds.FavorMilitary,
      },
      actions = {
        actionIds.Battle,
      },
      special = true,
      partisan = factionIds.Afghan,
      prize = nil,
    },
    [1803] = {
      cardNum = 4,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Spy
      },
      actions = {
        actionIds.Gift,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1804] = {
      cardNum = 5,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Tribe
      },
      actions = {
        actionIds.Build
      },
      special = true,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [2302] = {
      cardNum = 6,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Build,
        actionIds.Battle,
      },
      special = false,
      partisan = factionIds.Afghan,
      prize = nil,
    },
    [1806] = {
      cardNum = 7,
      rank = 2,
      suit = suitIds.Political,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Tribe,
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {},
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1807] = {
      cardNum = 8,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Spy,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Tax
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1808] = {
      cardNum = 9,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1809] = {
      cardNum = 10,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.FavorMilitary,
      },
      actions = {
        actionIds.Build,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1810] = {
      cardNum = 11,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
      },
      actions = {
        actionIds.Tax,
        actionIds.Gift,
      },
      special = false,
      partisan = factionIds.Afghan,
      prize = nil,
    },
    [1811] = {
      cardNum = 12,
      rank = 3,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1812] = {
      cardNum = 13,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Build,
        onPlayedIds.Build,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = nil,
    },
    [2303] = {
      cardNum = 14,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Gift,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [2100] = {
      cardNum = 15,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Army
      },
      actions = {
        actionIds.Betray
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1815] = {
      cardNum = 16,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Tax,
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1816] = {
      cardNum = 17,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Kabul,
      onPlayed = {
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Build,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1817] = {
      cardNum = 18,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Gift,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1818] = {
      cardNum = 19,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.March,
        actionIds.Betray,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1819] = {
      cardNum = 20,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.FavorEconomic
      },
      actions = {
        actionIds.Gift,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1600] = {
      cardNum = 21,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March
      },
      special = true,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1601] = {
      cardNum = 22,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.March,
        actionIds.Gift,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1602] = {
      cardNum = 23,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1603] = {
      cardNum = 24,
      rank = 2,
      suit = suitIds.Political,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Betray
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1604] = {
      cardNum = 25,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Tribe,
      },
      actions = {
        actionIds.Tax
      },
      special = false,
      partisan = factionIds.Afghan,
      prize = factionIds.British,
    },
    [1605] = {
      cardNum = 26,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Betray
      },
      special = false,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1606] = {
      cardNum = 27,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Leverage
      },
      actions = {
        actionIds.Build
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1607] = {
      cardNum = 28,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Tax,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1608] = {
      cardNum = 29,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1609] = {
      cardNum = 30,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1610] = {
      cardNum = 31,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Tax,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1611] = {
      cardNum = 32,
      rank = 3,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.March
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Afghan,
    },
    [1612] = {
      cardNum = 33,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1613] = {
      cardNum = 34,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [1614] = {
      cardNum = 35,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1615] = {
      cardNum = 36,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Battle,
        actionIds.Betray,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Afghan,
    },
    [1616] = {
      cardNum = 37,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Afghan,
    },
    [1617] = {
      cardNum = 38,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Punjab,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [1618] = {
      cardNum = 39,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1619] = {
      cardNum = 40,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Afghan,
    },
    [1700] = {
      cardNum = 41,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Build,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1701] = {
      cardNum = 42,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Leverage,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Build,
      },
      special = true,
      partisan = factionIds.Afghan,
      prize = factionIds.Afghan,
    },
    [2304] = {
      cardNum = 43,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1703] = {
      cardNum = 44,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Build,
        actionIds.Tax,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1704] = {
      cardNum = 45,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Betray,
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1705] = {
      cardNum = 46,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Leverage,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1706] = {
      cardNum = 47,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Gift,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1707] = {
      cardNum = 48,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.March,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1708] = {
      cardNum = 49,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Tax,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1709] = {
      cardNum = 50,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1710] = {
      cardNum = 51,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
      },
      special = true,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [1711] = {
      cardNum = 52,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Battle,
        actionIds.Tax,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1712] = {
      cardNum = 53,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Kandahar,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1713] = {
      cardNum = 54,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1714] = {
      cardNum = 55,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1715] = {
      cardNum = 56,
      rank = 2,
      suit = suitIds.Political,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Tribe,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Betray,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1716] = {
      cardNum = 57,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Tribe,
      },
      actions = {
        actionIds.Betray,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [1717] = {
      cardNum = 58,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Gift,
        actionIds.Build,
      },
      special = false,
      partisan = factionIds.Afghan,
      prize = nil,
    },
    [1718] = {
      cardNum = 59,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Betray,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1719] = {
      cardNum = 60,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Tax,
        actionIds.Gift,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1900] = {
      cardNum = 61,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
      },
      actions = {
        actionIds.Tax,
      },
      special = false,
      partisan = nil,
      prize = nil,
      centerActions = true,
    },
    [1901] = {
      cardNum = 62,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.FavorPolitical,
      },
      actions = {
        actionIds.Gift,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1902] = {
      cardNum = 63,
      rank = 3,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Road,
      },
      actions = {
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1903] = {
      cardNum = 64,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Spy,
        onPlayedIds.FavorMilitary,
      },
      actions = {
        actionIds.Tax,
      },
      special = false,
      partisan = nil,
      prize = nil,
      centerActions = true,
    },
    [1904] = {
      cardNum = 65,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Military,
      },
      actions = {
        actionIds.Battle,
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1905] = {
      cardNum = 66,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Afghan,
    },
    [1906] = {
      cardNum = 67,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Herat,
      onPlayed = {
        onPlayedIds.Road,
      },
      actions = {
        actionIds.March,
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1907] = {
      cardNum = 68,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Tax,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1908] = {
      cardNum = 69,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Battle,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = factionIds.British,
      centerActions = true,
    },
    [1909] = {
      cardNum = 70,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
      },
      special = true,
      partisan = factionIds.Russian,
      prize = factionIds.Afghan,
    },
    [1910] = {
      cardNum = 71,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Gift,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Afghan,
    },
    [1911] = {
      cardNum = 72,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [1912] = {
      cardNum = 73,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Military,
      },
      actions = {
        actionIds.Build,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [1913] = {
      cardNum = 74,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Betray,
        actionIds.Battle,
      },
      special = false,
      partisan = factionIds.Afghan,
      prize = factionIds.Russian,
    },
    [1914] = {
      cardNum = 75,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Tax,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1915] = {
      cardNum = 76,
      rank = 2,
      suit = suitIds.Political,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Tribe,
        onPlayedIds.FavorIntelligence,
      },
      actions = {},
      special = false,
      partisan = nil,
      prize = nil,
    },
    [2305] = {
      cardNum = 77,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Build,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [1917] = {
      cardNum = 78,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Leverage,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Build,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [1918] = {
      cardNum = 79,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [1919] = {
      cardNum = 80,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.Build,
      },
      special = false,
      partisan = factionIds.British,
      prize = factionIds.Russian,
    },
    [2306] = {
      cardNum = 81,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.Build,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = factionIds.British,
    },
    [2001] = {
      cardNum = 82,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Gift,
        actionIds.Battle,
      },
      special = false,
      partisan = nil,
      prize = nil,
    },
    [2101] = {
      cardNum = 83,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Tax,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [2003] = {
      cardNum = 84,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Persia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Battle,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = factionIds.Afghan,
      centerActions = true,
    },
    [2004] = {
      cardNum = 85,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
        onPlayedIds.FavorEconomic,
      },
      actions = {
        actionIds.Gift,
        actionIds.Build,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2005] = {
      cardNum = 86,
      rank = 2,
      suit = suitIds.Intelligence,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Spy,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Build,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = nil,
    },
    [2006] = {
      cardNum = 87,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Gift,
        actionIds.Build,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = nil,
    },
    [2007] = {
      cardNum = 88,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Gift,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = nil,
    },
    [2008] = {
      cardNum = 89,
      rank = 1,
      suit = suitIds.Intelligence,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.March,
        actionIds.Betray,
        actionIds.Battle,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = nil,
    },
    [2009] = {
      cardNum = 90,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Tribe,
      },
      actions = {
        actionIds.Tax,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2010] = {
      cardNum = 91,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Betray,
      },
      special = true,
      partisan = nil,
      prize = factionIds.Russian,
    },
    [2011] = {
      cardNum = 92,
      rank = 1,
      suit = suitIds.Political,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Spy,
        onPlayedIds.FavorMilitary,
      },
      actions = {
        actionIds.Battle,
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2012] = {
      cardNum = 93,
      rank = 2,
      suit = suitIds.Political,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Tribe,
        onPlayedIds.Tribe,
      },
      actions = {
        actionIds.Battle,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2013] = {
      cardNum = 94,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Spy,
        onPlayedIds.Leverage,
      },
      actions = {
        actionIds.Tax,
        actionIds.Betray,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2014] = {
      cardNum = 95,
      rank = 1,
      suit = suitIds.Economic,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Road,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = factionIds.Afghan,
    },
    [2015] = {
      cardNum = 96,
      rank = 2,
      suit = suitIds.Economic,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Road,
        onPlayedIds.Road,
      },
      actions = {
        actionIds.Tax,
        actionIds.March,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2016] = {
      cardNum = 97,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.FavorIntelligence,
      },
      actions = {
        actionIds.Build,
      },
      special = true,
      partisan = nil,
      prize = nil,
    },
    [2017] = {
      cardNum = 98,
      rank = 3,
      suit = suitIds.Military,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Gift,
      },
      special = false,
      partisan = nil,
      prize = factionIds.British,
    },
    [2018] = {
      cardNum = 99,
      rank = 1,
      suit = suitIds.Military,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Spy,
      },
      actions = {
        actionIds.Battle,
      },
      special = true,
      partisan = factionIds.Russian,
      prize = factionIds.British,
    },
    [2019] = {
      cardNum = 100,
      rank = 2,
      suit = suitIds.Military,
      region = regionIds.Transcaspia,
      onPlayed = {
        onPlayedIds.Army,
        onPlayedIds.Army,
      },
      actions = {
        actionIds.Battle,
      },
      special = false,
      partisan = factionIds.Russian,
      prize = factionIds.British,
    }
  }
  
end 